Repository augmentmy-world/artoolkitX.js, pull requests merged in 2019-08, with the labels that each got.

#17 Fix for the ajax function and other related issues
  Source/artoolkitX.api.js
Labels: bug, enhancement, javascript

#21 updated version.txt and Readme.md
  README.md
  version.txt
Labels: bug, building process, enhancement

#23 api rework
  README.md
  Source/artoolkitX.api.js
Labels: code design, enhancement, javascript
